### ISSUE TITLE
Pending migration and test suite errors

### ISSUE THREAD

**Issue by alexbarron** [learn-co-curriculum/model-class-methods-lab#15]
Have had a number of issues with this lab. Originally had a problem where I didn't have ruby 2.2.0 installed. This lab sets the ruby version as 2.2.0 in the Gemfile and .ruby-version files. Installing ruby 2.2.0 didn't end up solving the issue.

I asked Learn support for help and they told me 2.2.3(the version I've been using all this time) should work fine for this lab.

After deleting the ruby version in the Gemfile and .ruby-version to mimic past Rails labs, things appeared to work. See my commit here: https://github.com/alexbarron/model-class-methods-lab-v-000/commit/f6339f11b52e6ef5e0865b223eb0ac3eb1501724

I ran 'rake db:migrate RAILS_ENV=test' and this ran fine. I ran the test suite and that ran fine.

However, running the test suite a second time results in the following error:

```
♥ learn
/Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/activerecord-4.2.0/lib/active_record/migration.rb:393:in `check_pending!':  (ActiveRecord::PendingMigrationError)

Migrations are pending. To resolve this issue, run:

	bin/rake db:migrate RAILS_ENV=test

	from /Users/alexbarron/Development/code/model-class-methods-lab-v-000/spec/spec_helper.rb:13:in `<top (required)>'
	from /Users/alexbarron/Development/code/model-class-methods-lab-v-000/spec/models/boat_spec.rb:1:in `require'
	from /Users/alexbarron/Development/code/model-class-methods-lab-v-000/spec/models/boat_spec.rb:1:in `<top (required)>'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `load'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `each'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:97:in `setup'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:85:in `run'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:70:in `run'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/lib/rspec/core/runner.rb:38:in `invoke'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.2.1/exe/rspec:4:in `<top (required)>'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `load'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/bin/rspec:23:in `<main>'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/alexbarron/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

Running rake:db migrate RAILS_ENV=test again results in this error(below is shortened version):

```
♥ rake db:migrate RAILS_ENV=test
== 20140313192355 CreateBoats: migrating ======================================
-- create_table(:boats)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "boats" already exists: CREATE TABLE "boats" ("id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, "name" varchar, "length" integer, "captain_id" integer, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL) /Users/alexbarron/.rvm/gems/ruby-2.2.3/gems/sqlite3-1.3.10/lib/sqlite3/database.rb:91:in `initialize'
```

Running rake db:reset RAILS_ENV=test allows me to migrate the test DB again, run the tests one more time, but then returns the same error as before.

Ian from Learn.co chat support was able to reproduce this error and he recommended I raise this as an issue.

**Comment by aturkewi** [comment]
I can fix this issue by commenting out line 13 of the spec_helper.rb: `ActiveRecord::Migration.check_pending! if defined?(ActiveRecord::Migration)`, but this feels more like a workaround, than a true solution.

**Comment by aturkewi** [comment]
We could also comment out line 25 of the same file `ActiveRecord::Base.subclasses.each(&:delete_all)`. I'm wondering if the real solution is to use something like database cleaner here?

**Comment by aturkewi** [comment]
@PeterBell

**Comment by PeterBell** [comment]
Hey @pletcher is this something you might be able to check into? cc @AnnJohn

**Comment by pletcher** [comment]
It looks like the `migrations` table was getting dropped between tests. I pushed a fix -- lemme know if the problem still comes up!

**Comment by alexbarron** [comment]
Thanks @pletcher, it works now! ")

Still have to comment out 'ruby 2.2.0' from the Gemfile. This isn't a big deal, but small extra step for people who don't have 2.2.0 installed already.

Most of the other labs don't specify a ruby version. Would this lab still work without specifying a ruby version?

**Comment by pletcher** [comment]
The lab should work with that line commented out (and the .ruby-version file removed) -- installing v2.2.0 with rbenv or RVM doesn't work?

**Comment by PeterBell** [comment]
Awesome - thanks so much for knocking this out @pletcher - great stuff :smile_cat:

**Comment by alexbarron** [comment]
Yep, it works fine by commenting out 2.2.0. Don't even need to delete the .ruby-version file.

Installing 2.2.0 with rvm yielded another error where bash commands didn't work. I forget the exact error message but it was something like "bash: learn: command not found". 'bundle' also was not found.

Not a big deal of course, but it might be a little more user friendly if no ruby specific version was required.

**Comment by pletcher** [comment]
Right, so the trouble is that rvm doesn't have `learn` (the `learn-co` gem) or `bundle` (the `bundler` gem) installed under Ruby 2.2.0, only under the Ruby that you've been using.

Does rvm give a helpful error about this (like mentioning which Rubies _do_ have those commands available)? I use [rbenv](https://github.com/rbenv/rbenv), which offers just such an error in these cases.

It's pretty common (and, in the end, a bit stabler) to specify a Ruby version, so I'm inclined to keep that part; but if rvm isn't being helpful, we can make sure to mention that students might encounter this issue in an earlier lesson. (It's something that one encounters pretty regularly working in a Ruby shop, so it's good to know about.)
