### ISSUE TITLE
The tests are not able to pass at all. 

### ISSUE THREAD

**Issue by Louiefigz** [learn-co-curriculum/model-class-methods-lab#16]
I've been on this lab for a little while trying to figure out whyI'm not able to get those tests passing even when using the exact same code in the solution branch. My errors are coming from the Boat Model of this lab.  Even attempting to solve the lab with the find_by() method is not useful because rspec uses the pluck method to pull the information. 

Im not sure why I have duplicate boats when I migrate only once and the tests are only creating the objects once. 

Boat
  ::first_five
    returns the first five Boats
  ::dinghy
    returns boats shorter than 20 feet
  ::ship
    returns boats 20 feet or longer
  ::last_three_alphabetically
    returns last three boats in alphabetical order (FAILED - 1)
  ::without_a_captain
    returns boats without a captain (FAILED - 2)
  ::sailboats
    returns all boats that are sailboats (FAILED - 3)
  ::with_three_classifications
    returns boats with three classifications (FAILED - 4)

Captain
  ::catamaran_operators
    returns all captains of catamarans (FAILED - 5)
  ::sailors
    returns captains with sailboats (FAILED - 6)
  ::talented_seamen
    returns captains of motorboats and sailboats (FAILED - 7)
  ::non_sailors
    returns people who are not captains of sailboats (FAILED - 8)

Classification
  ::my_all
    returns all classifications (FAILED - 9)
  #longest
    returns the classifications for the longest boat (FAILED - 10)

Failures:

  1) Boat::last_three_alphabetically returns last three boats in alphabetical order
     Failure/Error: expect(Boat.last_three_alphabetically.pluck(:name)).to eq(boats)
       
       expected: ["Zodiac CZ7", "Triton 21 TRX", "Sunfish"]
            got: ["Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7"]
       
       (compared using ==)
     # ./spec/models/boat_spec.rb:28:in `block (3 levels) in <top (required)>'

  2) Boat::without_a_captain returns boats without a captain
     Failure/Error: expect(Boat.without_a_captain.pluck(:name)).to eq(boats)
       
       expected: ["Harpoon 4.7", "Sunfish"]
            got: ["Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish", "Harpoon 4.7", "Sunfish"]
       
       (compared using ==)
     # ./spec/models/boat_spec.rb:35:in `block (3 levels) in <top (required)>'

  3) Boat::sailboats returns all boats that are sailboats
     Failure/Error: expect(Boat.sailboats.pluck(:name)).to eq(boats)
       
       expected: ["H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish"]
            got: ["H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish", "H 28", "Nacra 17", "49er", "Laser", "Harpoon 4.7", "Sunfish"]
       
       (compared using ==)
     # ./spec/models/boat_spec.rb:42:in `block (3 levels) in <top (required)>'

  4) Boat::with_three_classifications returns boats with three classifications
     Failure/Error: expect(Boat.with_three_classifications.pluck(:name).sort).to eq(boats)
       
       expected: ["Nacra 17", "Sun Tracker Regency 254 XP3", "Zodiac CZ7"]
            got: ["Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Nacra 17", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Sun Tracker Regency 254 XP3", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7", "Zodiac CZ7"]
       
       (compared using ==)
     # ./spec/models/boat_spec.rb:49:in `block (3 levels) in <top (required)>'

**Comment by pletcher** [comment]
Hi @Louiefigz -- I checked out your code, and it looks like you'll need to pull some updates from this repository. Note the difference between [the current spec_helper.rb](https://github.com/learn-co-curriculum/model-class-methods-lab/blob/master/spec/spec_helper.rb) and [your spec_helper.rb](https://github.com/Louiefigz/model-class-methods-lab-v-000/blob/master/spec/spec_helper.rb). The [latest three commits](https://github.com/learn-co-curriculum/model-class-methods-lab/commits/master) should provide clues on what's missing.

That should make it so that tests basically run -- I'm seeing a few undefined method errors when I run tests against your code locally, so you might want to take a look at those. The current solution branch of this repository passes.
