### ISSUE TITLE
spec_helper configuration breaks rspec

### ISSUE THREAD

**Issue by authorbeard** [learn-co-curriculum/model-class-methods-lab#17]
When I ran rspec, then tried to run it again, I got an error saying migrations were pending. But they weren't, so running them again resulted in aborted migrations. So I was resetting the database after every run. I just lost a day thinking it was something to do with my environment and testing everything I wrote in rails console so I could run rspec once (always works the first time) on a batch of methods between resets, because I couldn't find anything at all that would help fix this. When I noticed the migrations error arising even when I hadn't changed anything in my code, I dug around until I found something pointing at line 16. 

Here's what it was: 
`config.use_transactional_fixtures = false`

I changed it to "true" and it worked. Spent 2 hours on Ask trying to figure this out. We haven't covered anything in Rspec yet, so I didn't know where to begin looking. My methods still aren't all working and this lesson is already confusing enough as it is (the readme mentions Arel out of the blue and sends us to some fruitless documentation), so I've basically lost an entire day to this. It's extremely frustrating.

**Comment by pletcher** [comment]
It makes sense that changing that setting would fix the issues you were seeing, but you're also running a slightly outdated version of the specs that was doing weird things for test setup. I've fixed the weird setup, so I'm going to close this issue.
