### ISSUE TITLE
learn and rspec not working properly

### ISSUE THREAD

**Issue by fiveinfinity** [learn-co-curriculum/model-class-methods-lab#18]
after running `rake db:migrate` and `rake db:migrate RAILS_ENV=test`, learn and rspec files will only run once. After that it prompts to re-run `rake db:migrate RAILS_ENV=test` which throws an error every time (it won't migrate). The only solution @the-widget found was to delete the test.sqlite3 file and run `rake db:migrate RAILS_ENV=test`, however you have to do this everytime you want to run a test.

**Comment by AnnJohn** [comment]
hi @fiveinfinity thanks for raising this. We'll look into this one within the next week and fix as needed.

**Comment by pletcher** [comment]
You should update your fork:

https://github.com/fiveinfinity/model-class-methods-lab-v-000/blob/master/spec/spec_helper.rb 

vs.

https://github.com/learn-co-curriculum/model-class-methods-lab/blob/master/spec/spec_helper.rb <-- this is the up-to-date version
