### ISSUE TITLE
Should we do this lab earlier?

### ISSUE THREAD

**Issue by StevenNunez** [learn-co-curriculum/model-class-methods-lab#2]
This lab, or a lab like this could be done during SQL, or early sinatra. There aren't any routes in this lab.

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by pletcher** [comment]
Looks like this has been iceboxed for a while -- any updates? @StevenNunez @AnnJohn

**Comment by StevenNunez** [comment]
I guess not really an issue with the lab but with the track. I'll update it.

**Comment by StevenNunez** [comment]
@pletcher ^^
