### ISSUE TITLE
Rspec not cleaning up the database

### ISSUE THREAD

**Issue by rmullig2** [learn-co-curriculum/model-class-methods-lab#21]
The spec_helper code to clean the database is not working:

config.after do
    (ActiveRecord::Base.subclasses - [ActiveRecord::SchemaMigration]).each(&:delete_all)
  end

I am manually deleting the database and migrating each time as a workaround but can somebody look into this?

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
