### ISSUE TITLE
No Need for Arel

### ISSUE THREAD

**Issue by snsavage** [learn-co-curriculum/model-class-methods-lab#22]
Maybe I misunderstood the intention of this lab, but adding the Arel references is confusing.  I appreciate knowing that Arel is the underpinning of ActiveRecord, but suggesting to  build these queries with Arel seems to be unnecessary.  The solution doesn't use any Arel, so there is no way to check on solutions.  

Also, the solution provided uses some nice tricks, and I've seen some solutions like this before.  For instance using the "id" field with where and the "&" operator.  I'm sure not if there are best practices instead of trying to built one single query.  

Perhaps clarifying the inclusion of the Arel information and providing a few suggestions on query construction would be helpful in this lab.

**Comment by kyleblee** [comment]
I realize it's been a while since this was posted but I just want to add a +1 to what @snsavage is saying here. The resources are not helpful for understanding how to solve the lab and there is 0 discussion of AREL in the lesson that precedes it. I feel like I'm coming at this lacking the background knowledge necessary to solve it.

**Comment by kyleblee** [comment]
This would have been a much more helpful resource: 
http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
