### ISSUE TITLE
Clicking Open on lesson page results in 'not found' Learn-IDE error.

### ISSUE THREAD

**Issue by jcpny1** [learn-co-curriculum/model-class-methods-lab#23]
Clicking Open button on page:
https://learn.co/tracks/full-stack-web-dev-with-react/rails/refactoring-with-helpers-and-model-methods/model-class-methods-lab#

Results in the following Learn-IDE error:
learn open model-class-methods-lab-v-000                                                            
Looking for lesson...                                                                               
Hmm...Cannot find lesson with repo: model-class-methods-lab-v-000. Please check your input and try a
gain.                                                                                               
[19:44:22] labs                                                                                     
// ♥

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
