### ISSUE TITLE
Captain Non Sailors Test Wrong

### ISSUE THREAD

**Issue by FreeBreadsticks** [learn-co-curriculum/model-class-methods-lab#25]
In the ::non_sailors test it expects three captains for a result. According to the data given in seeds there are six captains that don't have sailboats.
`h_28.classifications << [ketch, sailboat]
nacra_17.classifications << [catamaran, sloop, sailboat]
regulator.classifications << [motorboat, center]
zodiac.classifications << [rib, motorboat, center]
boston_whaler.classifications << [motorboat]
forty_niner.classifications << [sailboat, sloop]
cape_dory.classifications << [motorboat, trawler]
laser.classifications << [sailboat, cat_rig]
triton.classifications << [motorboat, bass]
sun_tracker.classifications << [motorboat, pontoon, catamaran]
harpoon.classifications << [sailboat, sloop]
sunfish.classifications << [sailboat, cat_rig]`

I fixed it here by having it expect the correct amount of captains:
`describe "::non_sailors" do
    it "returns people who are not captains of sailboats" do
      captains = ["Captain Cook", "Captain Kidd", "William Kyd", "Arel English", "Henry Hudson", "Samuel Axe"]
      expect(Captain.non_sailors.pluck(:name)).to eq(captains)
    end`

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
