### ISSUE TITLE
Students seem confused by AREL documentation being the only provided resource, this lab should also link the AR QueryMethods API

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/model-class-methods-lab#26]
My suggestion is to include a link to the ActiveRecord::QueryMethods API first as this is the documentation the student is likely going to want to see to progress through this lab: http://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
