### ISSUE TITLE
more information would be helpful

### ISSUE THREAD

**Issue by williamhancharek** [learn-co-curriculum/model-class-methods-lab#27]
I was very confused/lost on how one should reference other models 

"..require writing more than one method in more than one model."

It would have been helpful to have some examples, as I did not fully understand what was meant by that statement, and I ended up somehow doing the lab without really crossreferencing any methods between models

**Comment by ICanDoAllThingThroughChrist** [comment]
i concurred as more examples of the "3 classification" would help in ID value which we are expected to write for.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
