### ISSUE TITLE
This should note that you should use a rails command 

### ISSUE THREAD

**Issue by gveve** [learn-co-curriculum/model-class-methods-lab#28]
This lab should not that you have to use the rails command "rails console" instead of rake console.

Also the file structure does not match what the prior read me has indicated.

ALSO AREL who knows what that is yet???

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
