### ISSUE TITLE
i concur with some of the inputs 

### ISSUE THREAD

**Issue by aisayo** [learn-co-curriculum/model-class-methods-lab#29]
After reading this article, I feel like the AREL resource should be replaced with this. 

http://guides.rubyonrails.org/active_record_querying.html

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
