### ISSUE TITLE
not really arel, no resources

### ISSUE THREAD

**Issue by SophieDeBenedetto** [learn-co-curriculum/model-class-methods-lab#3]
this lab isn't really using arel. and we don't explain diff between arel and regular active record query and we give very sparse resources. 

should includes

 http://tomdallimore.com/blog/includes-vs-joins-in-rails-when-and-where/

http://jeremysklarsky.github.io/blog/2015/03/15/the-sql-was-better-than-the-original/

**Comment by AnnJohn** [comment]
Iceboxing for now

**Comment by jmburges** [comment]
Hey @AnnJohn can you rename this lab to model-class-methods-lab and then ask the engineering team to update it in their system? 

@StevenNunez are you ok with that name?

**Comment by StevenNunez** [comment]
@jmburges Sure. Or something like Complex ActiveRecord Queries.
