### ISSUE TITLE
expect(Boat.with_three_classifications.pluck(:name).sort).to eq(boats)

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/model-class-methods-lab#30]
with the the subject test lacking values for writing the query, it has become a mystery as to what to query for.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
