### ISSUE TITLE
/usr/local/rvm/gems/ruby-2.3.1/gems/railties-4.2.0/lib/rails/commands/console.rb:29:in `bloc k in parse_arguments': invalid option: -b (OptionParser::InvalidOption)

### ISSUE THREAD

**Issue by ICanDoAllThingThroughChrist** [learn-co-curriculum/model-class-methods-lab#31]
can not open rails console due to subject error

**Comment by drakeltheryuujin** [comment]
Hi @ICanDoAllThingThroughChrist,

I'm having difficulty reproducing the issue, so I'm going to close it for now.

If you can provide further detail about the steps required to reproduce the issue and any additional relevant information about your development environment (local or IDE), I'd be happy to take a second look!

As always, thanks for contributing! 💙
