### ISSUE TITLE
Does not open automatically with open ide button. 

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/model-class-methods-lab#32]
Multiple attempts made and refreshed the page twice. I was able to manually fork and clone it.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
