### ISSUE TITLE
This lab does not open properly.

### ISSUE THREAD

**Issue by ylhoony** [learn-co-curriculum/model-class-methods-lab#33]
This lab does not pull the repo properly in either IDE Download or Browser. 
had to use refresh_ssh, then whenever I close IDE, and open again, it does not connect again.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We are in the process of updating the materials in this section and will be rewriting this lesson to address the current issues.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced. 💙
