### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by maxwellbenton** [learn-co-curriculum/model-class-methods-lab#39]
Problems: 
- Readme needs rewrite/Removal of bad resource content:

"This is the most frustrating lab in this curriculum yet. Not because it is hard. But because there is no teaching or guidance."

"After reading this article, I feel like the AREL resource should be replaced with this.http://guides.rubyonrails.org/active_record_querying.html"

"I was very confused/lost on how one should reference other models

"..require writing more than one method in more than one model."

It would have been helpful to have some examples, as I did not fully understand what was meant by that statement, and I ended up somehow doing the lab without really crossreferencing any methods between models"

"This lab should not that you have to use the rails command "rails console" instead of rake console.

Also the file structure does not match what the prior read me has indicated.

ALSO AREL who knows what that is yet???"

- Issues reports on lab opening/completion errors:

"Clicking Open button on page:
https://learn.co/tracks/full-stack-web-dev-with-react/rails/refactoring-with-helpers-and-model-methods/model-class-methods-lab#

Results in the following Learn-IDE error:
learn open model-class-methods-lab-v-000
Looking for lesson...
Hmm...Cannot find lesson with repo: model-class-methods-lab-v-000. Please check your input and try a
gain.
[19:44:22] labs
// ♥"

"Have re-forked and resubmitted this lab multiple times, all to no avail. Lesson page shows as completed, even having the "Next Lesson" and Solution buttons pop up. However, it doesn't show up as completed on my profile progress counter nor the curriculum tab."

"This lab does not pull the repo properly in either IDE Download or Browser.
had to use refresh_ssh, then whenever I close IDE, and open again, it does not connect again."

"Multiple attempts made and refreshed the page twice. I was able to manually fork and clone it."

- Lack of information/guidance
- Test problems, rspec doesn't drop database when run:

"My pairing partner (and most students) use the .find method in order to find the first_five instances in the database. However, .first returns an array and pluck expects an active_record_relation which causes the test to fail even though the information looks identical. I believe it is a good idea to change the spec file so we can use the .find function."

"In the ::non_sailors test it expects three captains for a result. According to the data given in seeds there are six captains that don't have sailboats.
h_28.classifications << [ketch, sailboat] nacra_17.classifications << [catamaran, sloop, sailboat] regulator.classifications << [motorboat, center] zodiac.classifications << [rib, motorboat, center] boston_whaler.classifications << [motorboat] forty_niner.classifications << [sailboat, sloop] cape_dory.classifications << [motorboat, trawler] laser.classifications << [sailboat, cat_rig] triton.classifications << [motorboat, bass] sun_tracker.classifications << [motorboat, pontoon, catamaran] harpoon.classifications << [sailboat, sloop] sunfish.classifications << [sailboat, cat_rig]

I fixed it here by having it expect the correct amount of captains:
describe "::non_sailors" do it "returns people who are not captains of sailboats" do captains = ["Captain Cook", "Captain Kidd", "William Kyd", "Arel English", "Henry Hudson", "Samuel Axe"] expect(Captain.non_sailors.pluck(:name)).to eq(captains) end"

"I don't see how this test can pass. I've manually checked the data, and there appear to be 6 captains of Motorboats and Sailboats, not 2. Unless the wording needs to be changed to indicate that you want those captains who have captained a Motorboat AND a Sailboat.

Failures:

Captain::talented_seamen returns captains of motorboats and sailboats
expected: ["Captain Cook", "Samuel Axe"]
got: ["Captain Cook", "Captain Kidd", "William Kyd", "Arel English", "Henry Hudson", "Samuel Axe"]"

**Comment by meg-gutshall** [comment]
^^ **ALL OF THIS** ^^

Also it would help to be exposed to the subject material before we're asked to complete a lab on it. The lesson before this lab had nothing to do with AREL. The only reason I knew you could even inject SQL into ActiveRecord was from a study session. This was over 4 hours that could have been put toward furthering my progress in the curriculum instead of working on a lab with **known issues** such as **broken tests** and **unclear instructions**. Please try to see how frustrating this is to a student who is struggling to pay the bills while making this career change work—every hour counts!

@aviflombaum @garettarrowood @sammarcus @veverkap

**Comment by drakeltheryuujin** [comment]
Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum. 

@maxwellbenton @sgharms is it possible to just un-deploy this lesson until it can be prioritized for a rewrite with the additional supporting content that students need? In the meantime, we can try to fix the tests but overall, it sounds frustrating.

Thanks for contributing! 💙
