### ISSUE TITLE
The Arel documentation has moved

### ISSUE THREAD

**Issue by NStephenson** [learn-co-curriculum/model-class-methods-lab#40]
Arel is now integrated into Active Record, so the current link to the documentation shows nothing of value. The link to refer to is here: https://guides.rubyonrails.org/active_record_querying.html

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
