### ISSUE TITLE
Bundle fails on install

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/model-class-methods-lab#41]
# Bundle fails on install

## Expected Behavior

`bundle` or `bundle install` installs dependencies 

## Observed Behavior

`bundle` or `bundle install` fails with incompatible version 

```
// ♥ bundle
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    rails (= 4.2) was resolved to 4.2.0, which depends on
      bundler (>= 1.3.0, < 2.0)

  Current Bundler version:
    bundler (2.0.1)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?

Could not find gem 'bundler (>= 1.3.0, < 2.0)', which is required by gem 'rails (= 4.2)', in
any of the sources.
```

## Cause 

[Breaking changes in Bundler v2.0](https://bundler.io/v2.0/whats_new.html#breaking-changes)

One of the features of Bundler v2.0 is version is "version autoswitching", which you can read about [here](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html). This feature requires a `Gemfile.lock` to be committed into VC, and the `Gemfile.lock` is currently `.gitignore`d. 

## Remedy

Check in `Gemfile.lock` to git. Output below shown on commit c853032, which was immediately prior to `Gemfile.lock` being removed from git: 

```
[16:05:51] ((HEAD detached at c853032)) model-class-methods-lab-v-000
// ♥ bundle
Fetching gem metadata from https://rubygems.org/..........
======
snip
======
Bundle complete! 12 Gemfile dependencies, 62 gems now installed.
```

#Staff

**Comment by AspenJames** [comment]
# Important! 
This will affect all labs without a `Gemfile.lock` checked into git wherein a dependency depends on `bundler, >2.0`

**Comment by heavenlyboheme** [comment]
Gemfile.lock is created after running "bundle install" in the terminal.

**Comment by AspenJames** [comment]
Yes, this is true. What I'm referencing above is a unique failure where a breaking change in Bundler v.2.0 is causing `bundle install` to fail. A `Gemfile.lock` file is necessary for the auto-version switching to happen. Since it's not there to begin with, the autoswitching doesn't occur, the dep install fails, and no lockfile is created. We've observed this issue in several students' environments, and while there is a workaround, adding a lockfile is a solution that prevents the failure from ever happening
