### ISSUE TITLE
Self-Paced Lesson "Optimal Queries using Active Record" link redirects/out of date

### ISSUE THREAD

**Issue by pekellogg** [learn-co-curriculum/model-class-methods-lab#65]
### Canvas Link

https://learning.flatironschool.com/courses/1881/assignments/125549?module_item_id=259444

### Concern

Hi FI team,

Two "AREL documentation" links redirect to the RoR Guide at https://guides.rubyonrails.org/active_record_querying.html. 

This is somewhat confusing as the lesson refers to the AREL documentation specifically and suggests the user to reference that directly. 

TY for your help!

### Additional Context

This might be due to AREL being moved from an independent Ruby gem to now be wrapped within the Active Record gem itself.

As of ~May 2020, the Rails Core team "consider Arel private API of the framework and we don’t recommend developers to use."

Link to discussion for reference:
https://discuss.rubyonrails.org/t/what-has-happened-to-arel/74383/6

**Comment by lizbur10** [comment]
Hi @pekellogg! Thanks for bringing this to our attention. I have updated the lesson to remove the references to the AREL library.

Thanks for contributing to the Flatiron School curriculum 💙
